# Valheim image version
# ref: https://github.com/lloesche/valheim-server-docker
image: lloesche/valheim-server
imageTag: latest

replicaCount: 1

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 6G
    cpu: 4.0

# Environment variables to be pulled from k8s secrets
# The secret key must exactly match the environment variable name.
envSecrets:
  SERVER_PASS: "valheim-secrets"
  #SUPERVISOR_HTTP_PASS: "valheim-secrets"

# Values in 'env' will be passed in as environment variables.
# Do not set any environment vars here that you want to pull from k8s secrets. use 'envSecrets'.
env:
  SERVER_NAME: "Valheim on Kubernetes"
  SERVER_PORT: 2456
  SERVER_ARGS: "-crossplay"


  ## Supervisor enable and config
  #SUPERVISOR_HTTP: "true"
  SUPERVISOR_HTTP_PORT: 9001

  ## valheim plus enable and config
  #VALHEIM_PLUS: true
  #VALHEIM_PLUS_REPO: Grantapher/ValheimPlus
  #VPCFG_VALHEIMPLUS_SERVERBROWSERADVERTISEMENT: "false"


service:
  prefix: valheim #prefix to use for service and port names (<prefix>-1 through <prefix>-3), and <prefix>-supervisor-http if enabled
  #specify starting port in 'env.SERVICE_PORT'
  game:
    type: LoadBalancer
  supervisor:
    type: LoadBalancer



persistence:
  config:
    enabled: true
    size: 10Gi
    storageClassName: local-path
  claimName: "" # provide a value to prevent PVC creation
