apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-server"
  labels:
    app: "{{ .Chart.Name }}-server"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-server"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-server"
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}-server"
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- if or $.Values.env $.Values.envSecrets }}
        env:
          {{- range $key, $value := $.Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $secret := $.Values.envSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $secret }}
                key: {{ $key | quote }}
          {{- end }}
        {{- end }}

        ports:
        - name: {{ .Values.service.prefix }}-1
          containerPort: {{ .Values.env.SERVER_PORT | int }}
          protocol: UDP
        - name: {{ .Values.service.prefix }}-2
          containerPort: {{ .Values.env.SERVER_PORT | int | add 1 }}
          protocol: UDP
        - name: {{ .Values.service.prefix }}-3
          containerPort: {{ .Values.env.SERVER_PORT | int | add 2 }}
          protocol: UDP

        # Enable Supervisor HTTP port if supervisor is enabled
        {{- if  $.Values.env.SUPERVISOR_HTTP }}
        - name: {{ .Values.service.prefix }}-web
          containerPort: {{ .Values.env.SUPERVISOR_HTTP_PORT | int }}
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: download
          mountPath: /opt/valheim
      volumes:
      - name: config
        {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          {{- if eq .Values.persistence.config.claimName "" }}
          claimName: "{{ .Chart.Name }}-config"
          {{- else }}
          claimName: {{ .Values.persistence.config.claimName }}
          {{- end }}
        {{- end }}

      - name: download
        {{- if .Values.persistence.download.enabled }}
        persistentVolumeClaim:
          {{- if eq .Values.persistence.download.claimName "" }}
          claimName: "{{ .Chart.Name }}-download"
          {{- else }}
          claimName: {{ .Values.persistence.download.claimName }}
          {{- end }}
        {{- end }}

