apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}-server"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if eq "LoadBalancer" .Values.service.type }}
  - name: {{ .Values.service.prefix }}-1
    port: {{ .Values.env.SERVER_PORT | int }}
    targetPort: {{ .Values.service.prefix }}-1
    protocol: UDP
  - name: {{ .Values.service.prefix }}-2
    port: {{ .Values.env.SERVER_PORT | int | add 1 }}
    targetPort: {{ .Values.service.prefix }}-2
    protocol: UDP
  - name: {{ .Values.service.prefix }}-3
    port: {{ .Values.env.SERVER_PORT | int | add 2 }}
    targetPort: {{ .Values.service.prefix }}-3
    protocol: UDP
  {{- else }}
  - name: {{ .Values.service.prefix }}-1
    port: {{ .Values.env.SERVER_PORT | int }}
    targetPort: {{ .Values.service.prefix }}-1
    nodePort: {{ .Values.env.SERVER_PORT | int }}
    protocol: UDP
  - name: {{ .Values.service.prefix }}-2
    port: {{ .Values.env.SERVER_PORT | int | add 1 }}
    targetPort: {{ .Values.service.prefix }}-2
    nodePort: {{ .Values.env.SERVER_PORT | int | add 1 }}
    protocol: UDP
  - name: {{ .Values.service.prefix }}-3
    port: {{ .Values.env.SERVER_PORT | int | add 2 }}
    targetPort: {{ .Values.service.prefix }}-3
    nodePort: {{ .Values.env.SERVER_PORT | int | add 2 }}
    protocol: UDP
  {{- end }}
  {{- if  $.Values.env.SUPERVISOR_HTTP }}
    {{- if eq "LoadBalancer" .Values.service.supervisor_type }}
  - name: {{ .Values.service.prefix }}-supervisor-http
    port: {{ .Values.env.SUPERVISOR_HTTP_PORT | int }}
    targetPort: {{ .Values.service.prefix }}-supervisor-http
    protocol: HTTP
    {{- else }}
  - name: {{ .Values.service.prefix }}-supervisor-http
    port: {{ .Values.env.SUPERVISOR_HTTP_PORT | int }}
    targetPort: {{ .Values.service.prefix }}-supervisor-http
    nodePort: {{ .Values.env.SERVER_PORT | int }}
    protocol: HTTP
    {{- end }}
  {{- end }}


  selector:
    app: "{{ .Chart.Name }}-server"
